// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkuziiubjtvickimapau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrdXppaXVianR2aWNraW1hcGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Njk1MDAsImV4cCI6MjA2OTM0NTUwMH0.VNKhPe_WdXC2grZJUlXLFTGT_qRI_7Tyoizv2HMO_0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});